### ISSUE TITLE
Removing default thresholds

### ISSUE THREAD

**Issue by adamgayoso** [JonathanShor/DoubletDetection#112]
This shouldn't be an optional parameter. Experimenters should create the threshold plot and choose their own thresholds.

**Comment by adamgayoso** [comment]
Alternatively, we can leave default thresholds, but print a mean statement about exploring the threshold space.

**Comment by adamgayoso** [comment]
I'm not sure we should do this any longer.

**Comment by JonathanShor** [comment]
Not even the mean statement?
