### ISSUE TITLE
NaN in doublets score

### ISSUE THREAD

**Issue by hwlim** [JonathanShor/DoubletDetection#115]
Hi

I noticed that sometimes I get NaN from the following command:

> doublets = clf.fit(raw_counts).predict(p_thresh=1e-7, voter_thresh=0.8)

Occasionally some elements in 'doublets' has NaN value, which nees some exception handling.
Is it safe to ignore this NaN value cells as non-doublets?

Thank you.

**Comment by adamgayoso** [comment]
NaN are cells that are not confidently assigned either label. I would inspect their location relative to the called doublets and make a decision from there. However, the simplest thing to do may be to call them singlets.

**Comment by hwlim** [comment]
Thank you so much for the detailed advice!
