### ISSUE TITLE
Allow alternative clustering

### ISSUE THREAD

**Issue by adamgayoso** [JonathanShor/DoubletDetection#120]
We should allow any clustering method to be used (either through scanpy or an alternative)

**Comment by adamgayoso** [comment]
This will not be implemented in 3.0. We instead use built in scanpy clustering, or PhenoGraph.

**Comment by kanefos** [comment]
Hi authors, really smart tool with great documentation, having a blast. Thought I'd reply on this topic: just wondering if you have any thoughts on using the Leiden versus Louvain algorithm for the BoostClassifier's _.one_fit method (line 325, replaced _sc.tl.louvain_ with _c.tl.leiden_. Ta!

**Comment by adamgayoso** [comment]
We can certainly add this as an option, but probably throw a user warning that it's experimental. We also need to give access to the resolution param.
