### ISSUE TITLE
organize file structure and decide how we want to run the final program

### ISSUE THREAD

**Issue by adamgayoso** [JonathanShor/DoubletDetection#16]
this is ongoing. No action necessary right now

**Comment by adamgayoso** [comment]
would like to comment that it appears we can take dataAcq and normalize counts and just put them in doublet detection. Makes sense to me to leave synthetic.py as is

**Comment by JonathanShor** [comment]
I could update test_run.py to take command line args for at a minimum the data file path.

What else should be user set-able?

**Comment by JonathanShor** [comment]
> I could update test_run.py to take command line args for at a minimum the data file path.
Initial at least done in #19.

**Comment by adamgayoso** [comment]
This should be done by Monday.

**Comment by JonathanShor** [comment]
At least everything in master should be clean by Monday (or the following Monday, really).
Prolly stop committing to master then too.
