### ISSUE TITLE
Doublet as Linear Combination of cell types likelihood eval

### ISSUE THREAD

**Issue by JonathanShor** [JonathanShor/DoubletDetection#18]
We define a doublet's gene expression profile as a linear combination of true cell types' profiles.

Given a doublet we've found, assign a likelihood for each cell types pairs as being the contributing profiles. Report the highest.

**Comment by JonathanShor** [comment]
Updating with the idea of defining cell types as a group of cell reads such that a linear downsampled doublet created from a random member pair is indistinguishable from the real group members with high probability.

**Comment by adamgayoso** [comment]
We still could trace the parents of the downsampled doublets and trace back what communities they came from

**Comment by JonathanShor** [comment]
Yeah, exactly. Gonna take a look at that.

Tho that's still relying on Phenograph for root clustering, right?

**Comment by adamgayoso** [comment]
yeah so I think you would store the indices of the parents and then see what clusters those are in in phenograph. See if there is some trend in doublets in identified doublet clusters

**Comment by adamgayoso** [comment]
following up with the proposition of an analysis of the boosted doublet parents vs identified doublet parents
