### ISSUE TITLE
doublet_rate is confusing to everyone I've explained this to

### ISSUE THREAD

**Issue by adamgayoso** [JonathanShor/DoubletDetection#35]
maybe we change the name of the parameter

**Comment by ryanbrand** [comment]
Maybe it would be more intuitive if we called it percent_synthetic or percent_doublets and made it equivalent to the percentage of the new dataset made up of doublets/synthetics

**Comment by JonathanShor** [comment]
My suggestion: `boost_rate`

**Comment by adamgayoso** [comment]
I like boost_rate.

**Comment by adamgayoso** [comment]
Just noting that this issue will be resolved in the class restructure

**Comment by JonathanShor** [comment]
Yes. The relevant commit is d657213118584ca28c077ee94703f6c212df3851.
