### ISSUE TITLE
Precision and Recall

### ISSUE THREAD

**Issue by adamgayoso** [JonathanShor/DoubletDetection#39]
Devise an experiment where we add fake doublets (5%) treat them as true  - allowing us to calculate precision and recall.

**Comment by JonathanShor** [comment]
The old synthetic.create_synthetic_data() [still in master as of ecf6f23479efebf6a724c87cdbc56bfa6509a509] was doing the production part, tho with some probabilistic synthetic specific calls. Should be straight forward to replace the relevant chunk(s?) with calls to downsampleCellPair(), I think?

The old miscellaneous.testModel() was providing (some level of) streamlined precision & recall reporting. Don't remember how relevant its input/output is now, but might still be a place to start from.
Hmm, actually, I think it may conform to what we're doing with the class restructure.
Here's the commit before it was removed: c459b69ddd225ba19697956f6ad5b8b05bdb2f92.

**Comment by JonathanShor** [comment]
@adamgayoso, you see this going into validation_script.py?

**Comment by adamgayoso** [comment]
yeah probably

**Comment by adamgayoso** [comment]
Closing this as it has been done in #42
