### ISSUE TITLE
How should the -1 "cluster" be handled?

### ISSUE THREAD

**Issue by JonathanShor** [JonathanShor/DoubletDetection#48]
Suggested behavior:

Default option: Rerun phenograph up to some preset number of times (3? 5?) until a clean (no -1s) clustering is found.
Otherwise, runtime error out with a suggestion to change a parameter.

Alternative options: Discard all -1s. Keep -1s as their own legit cluster. Keep them, but set their score to zero.
What else?

Currently (1.0), always keeping them as their own legit cluster.

**Comment by adamgayoso** [comment]
I think we need to revisit this, assigning a score of 0 to any cells in a -1 cluster

**Comment by adamgayoso** [comment]
I think this should tell you exactly how many didn't ever join a cluster instead of "one or more"
