### ISSUE TITLE
Prior doublet rate parameter

### ISSUE THREAD

**Issue by JonathanShor** [JonathanShor/DoubletDetection#54]
Add a parameter that indicates the expected doublet rate for the dataset.
Can be used by the score heuristic to omit any scores that would indicate a doublet rate higher than the parameter.

**Comment by adamgayoso** [comment]
I think we could create a function which outputs a figure, with a line indicating the prior expected doublet rate, allowing the user to see the impact of different thresholds

**Comment by adamgayoso** [comment]
I'm not sure how this could be implemented anymore. The mini viz suite in #72 will serve as a more manual diagnostic version of this.

**Comment by adamgayoso** [comment]
I'm not sure this is necessary anymore given the new plotting functions

**Comment by adamgayoso** [comment]
Closing this as it is no longer a future direction.
