### ISSUE TITLE
Input types for count matrix

### ISSUE THREAD

**Issue by adamgayoso** [JonathanShor/DoubletDetection#71]
We should at least accept:

- Sparse matrices
- Pandas DataFrames
- 10x mtx format

For sparse matrices, we will probably just instantly make them dense.

**Comment by JonathanShor** [comment]
If it seems worthwhile to fully support sparse in and out, there are some options for getting "around" PCA densifying the matrix, such as a random subsample PCA.
I'm not familiar with these approaches, so we'd have to look into them further.

**Comment by JonathanShor** [comment]
Likely use `sklearn.utils.check_array`.
