### ISSUE TITLE
memory requirement

### ISSUE THREAD

**Issue by lpantano** [JonathanShor/DoubletDetection#94]
Hi!

thanks a lot for work on this, it is very useful.

I was trying to work on the example data you have (thanks for doing that example).

I wanted to know how much memory it needs for that data, because I keep getting my job killed by memory issues and I went up to 64G. I want to make sure it is not a problem at my end (job actually not having that memory allocated) or if it really needs more than that.

Thanks a bunch!

**Comment by JonathanShor** [comment]
We've run it on a personal laptop with 16gb RAM without problem.

You could try setting a lower `n_top_var_genes` value, tho you should really be more than fine with 64gb with the default settings.

**Comment by lpantano** [comment]
Thanks for the information. I am going to try my personal laptop as well, maybe something is wrong with the cluster or python package installation.

Thanks a lot!

**Comment by adamgayoso** [comment]
@lpantano Were you able to figure out the problem?

**Comment by lpantano** [comment]
Hi,
Yes, at the end I tried in my computer and it works, but for some reason there is a memory leak or something when running in the linux cluster (I have a macosx). I created a conda environment to install this package, similar to what I did in my machine.

Not sure, if the problem is some package version or the linux machines or what. 

thanks!
